#!/usr/bin/env bash
#
# Generated by the HyperSpeed build-plan generator.
#
# Configures required-status-check branch protection on main so a
# session PR cannot merge until its "test" check is green. Run
# once, with admin permissions on the repo:
#
#   bash setup-branch-protection.sh
#
# It is visibility- and plan-aware:
#   - public repos, or private repos on a paid plan  → classic branch protection
#   - private repos on the GitHub Free plan          → repository rulesets
#     (classic protection 403s with an "upgrade" message there)
#
# The required check context "test" must match the job key in
# .github/workflows/session-tests.yml (jobs.test:). A mismatch
# would let PRs merge without the gate firing, so this script verifies the
# context after applying.
#
# #115 — CI-only gating (no required approving review). The runner enables
# GitHub auto-merge on sessions with NO manual acceptance criteria, so those
# PRs self-merge the moment the "test" check is green — no
# operator click. An approving review is therefore NOT required:
#   - required_approving_review_count is 0 (the CI status check is the gate;
#     the PR author — the runner — could never approve its own PR anyway).
#   - strict is false: within a wave, sessions own disjoint files, so a PR does
#     not need to be up to date with a sibling that merged first; serialising
#     them under `strict: true` would stall every auto-merge after the first.
#     The integration gate between waves is the real cross-session check.
# Sessions WITH manual ACs are left open by the runner for human sign-off (it
# does not enable auto-merge on them).
set -euo pipefail

BRANCH="main"
REQUIRED_CHECK="test"

command -v gh >/dev/null 2>&1 || { echo "✗ gh CLI not found on PATH — install from https://cli.github.com" >&2; exit 1; }
gh auth status >/dev/null 2>&1 || { echo "✗ gh is not authenticated — run 'gh auth login' (or export GH_TOKEN)" >&2; exit 1; }

REPO_FULL=$(gh repo view --json nameWithOwner -q .nameWithOwner)
OWNER=${REPO_FULL%%/*}
REPO=${REPO_FULL#*/}
VISIBILITY=$(gh repo view --json visibility -q .visibility | tr '[:upper:]' '[:lower:]')
echo "→ Repo: $REPO_FULL ($VISIBILITY), protecting branch '$BRANCH', required check '$REQUIRED_CHECK'"

# ── Decide classic protection vs rulesets ────────────────────────────────────
# Public repos always support classic protection. For private/internal repos,
# probe the classic protection endpoint: a 403 carrying "upgrade" means the
# Free-plan paywall, so fall back to rulesets (available on Free for private
# repos). Any other response (incl. 404 "Branch not protected") means classic
# protection is usable.
USE="classic"
if [ "$VISIBILITY" != "public" ]; then
  PROBE=$(gh api "repos/$OWNER/$REPO/branches/$BRANCH/protection" 2>&1 || true)
  if printf '%s' "$PROBE" | grep -qi "upgrade"; then
    USE="rulesets"
  fi
fi
echo "→ Using ${USE} for branch protection"

# ── Validate the required check actually exists ──────────────────────────────
# Look for recent runs of the session-tests workflow. If none exist yet the
# check context can't have appeared on any PR — warn rather than fail, since a
# first run will create it.
if gh run list --workflow=session-tests.yml --limit 1 >/tmp/hs-runs.txt 2>/dev/null && [ -s /tmp/hs-runs.txt ]; then
  echo "✓ session-tests.yml has run before — the '$REQUIRED_CHECK' check context exists"
else
  echo "⚠ No runs of session-tests.yml found yet. The '$REQUIRED_CHECK' check context"
  echo "  will not exist until a PR triggers the workflow. Open one session PR first,"
  echo "  let CI run, then re-run this script so the required check resolves."
fi

# ── Apply protection ─────────────────────────────────────────────────────────
if [ "$USE" = "classic" ]; then
  gh api -X PUT "repos/$OWNER/$REPO/branches/$BRANCH/protection" --input - <<JSON
{
  "required_status_checks": { "strict": false, "contexts": ["$REQUIRED_CHECK"] },
  "enforce_admins": false,
  "required_pull_request_reviews": { "required_approving_review_count": 0 },
  "restrictions": null
}
JSON
  # Verify the context landed.
  CONTEXTS=$(gh api "repos/$OWNER/$REPO/branches/$BRANCH/protection" -q '.required_status_checks.contexts | join(",")')
  if printf '%s' "$CONTEXTS" | grep -q "$REQUIRED_CHECK"; then
    echo "Verified: required_status_checks.contexts contains \"$REQUIRED_CHECK\""
  else
    echo "✗ Protection applied but contexts did not include \"$REQUIRED_CHECK\" (got: $CONTEXTS)" >&2
    exit 1
  fi
else
  # #132 F — On a PRIVATE repo under the GitHub Free plan, BOTH classic
  # protection AND repository rulesets 403 ("Upgrade to GitHub Pro or make this
  # repository public to enable this feature."). Capture the POST result so we
  # can turn that raw 403 into an actionable explanation instead of a cryptic
  # `set -e` abort. Don't let the failing call kill the script here.
  RULESET_OUT=$(gh api -X POST "repos/$OWNER/$REPO/rulesets" --input - 2>&1 <<JSON || true
{
  "name": "hyperspeed-session-gate",
  "target": "branch",
  "enforcement": "active",
  "conditions": { "ref_name": { "include": ["refs/heads/$BRANCH"], "exclude": [] } },
  "rules": [
    { "type": "pull_request",
      "parameters": { "required_approving_review_count": 0, "dismiss_stale_reviews_on_push": false, "require_code_owner_review": false, "require_last_push_approval": false, "required_review_thread_resolution": false } },
    { "type": "required_status_checks",
      "parameters": { "strict_required_status_checks_policy": false, "required_status_checks": [ { "context": "$REQUIRED_CHECK" } ] } }
  ]
}
JSON
)
  if printf '%s' "$RULESET_OUT" | grep -qiE "upgrade|HTTP 403"; then
    echo "✗ Branch protection is unavailable on this repo." >&2
    echo "  This is a PRIVATE repo on the GitHub Free plan: neither classic branch" >&2
    echo "  protection nor repository rulesets can require a status check there." >&2
    echo "" >&2
    echo "  Required-status-check gating (and GitHub auto-merge) need ONE of:" >&2
    echo "    • making this repository PUBLIC  (gh repo edit --visibility public), or" >&2
    echo "    • upgrading the owner to a PAID plan (GitHub Pro / Team / Enterprise)." >&2
    echo "" >&2
    echo "  Until then, run the build SUPERVISED and merge each PR by hand — the" >&2
    echo "  unattended self-merge path (#115) cannot be enabled on this plan/visibility." >&2
    exit 1
  fi
  # Verify a ruleset now requires the check.
  if gh api "repos/$OWNER/$REPO/rulesets" -q '.[].name' | grep -q "hyperspeed-session-gate"; then
    echo "Verified: required_status_checks.contexts contains \"$REQUIRED_CHECK\""
  else
    echo "✗ Ruleset POST did not create a 'hyperspeed-session-gate' ruleset." >&2
    echo "  Response was:" >&2
    printf '%s\n' "$RULESET_OUT" | sed 's/^/    /' >&2
    exit 1
  fi
fi

echo "✓ Branch protection configured for '$BRANCH'."
